apiVersion: v2
name: fume
description: A Helm chart for FUME Enterprise
type: application
version: 0.4.3
appVersion: "1.8.1"
maintainers:
  - name: Outburn Ltd.
keywords:
  - fume
  - fhir
  - mapping
  - healthcare
  - converter
home: https://github.com/Outburn-IL/fume-deployments
